### ISSUE TITLE
Support Python 2.6

### ISSUE THREAD

**Issue by tobinus** [tobinus/python-podgen#43]
When trying to add 2.6 support in issue #19, it turned out that some ugly hacks would have to be done to the tests, due to the missing support for unittest discovery and executing packages in 2.6. Also, everyone should just use 2.7 instead.

However, not everyone is able to move to 2.7. Comment on this issue if you need to have PodGen working on Python 2.6! I need to see how much demand there is for it.

**Comment by hugovk** [comment]
No comment so far == no demand?

I'm not using this module, but It's definitely time to drop 2.6, it's only getting harder to support with other packages dropping it too.

**Comment by tobinus** [comment]
Well, I can only assume there's no demand, but this is a fairly new module too so not too many have discovered it either. I also guess that if anyone were to use this module, they would be using it for a new project, and so they would be able to use a newer version of Python. But if anyone feels the need for this module on 2.6, feel free to let me know :)

**Comment by hugovk** [comment]
Here's the pip installs for podgen from PyPI for the last year (via `pypinfo -d 365 --percent --pip podgen pyversion`)

| python_version | percent | download_count |
| -------------- | -------: | --------------: |
| 2.7            |   51.1% |             46 |
| 3.4            |   23.3% |             21 |
| 3.6            |   15.6% |             14 |
| 3.5            |   10.0% |              9 |

**Comment by tobinus** [comment]
Well, it's soon time to drop support for 2.7 as well, so I'm laying this one dead.
