### ISSUE TITLE
podgen fails to write (UTF-8) encoded feed to file

### ISSUE THREAD

**Issue by ndkv** [tobinus/python-podgen#65]
When trying to write an UTF-8 encoded feed to file I get a 

    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 249: ordinal not in range(128)

generated by `fd.write(rss)` on [line 690 in podcast.py](https://github.com/tobinus/python-podgen/blob/master/podgen/podcast.py#L690). 

A solution is to use the `open` function from the `codecs` module and specify the encoding explicitly like so 

```python
with open(filename, "w", encoding=encoding) as fd:
    fd.write(rss)
```

Although this fixes the problem I feel that I'm "holding podgen wrong" and am mishandling my unicode strings somewhere else... any thoughts?

**Comment by ndkv** [comment]
Thank you for fixing this! 🙌🏻

**Comment by tobinus** [comment]
No problem! Thank you for your patience ^^
